server:
  port: 6688
  servlet:
    context-path: /netty-websocket
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
    cache: true
    enabled: true
